### PR TITLE
fix: catch error on setGreeting

### LINKED ISSUE #70: add some UI that does error handling for fn calls
Right now the example app does not notice errors on rpc calls and does not report them to the user

### LINKED ISSUE #391: Can't update template twice in new generated template
Screen Shot 2020-07-06 at 3 50 22 PM

Then update to add random characters and hit save. It goes through.

If I continue updating, the `save` button doesn't unlock a second time

Screen Shot 2020-07-06 at 3 50 37 PM

### LINKED ISSUE #397: App gets stuck showing progress when error occurs
Screen Shot 2020-07-07 at 10 43 27 PM

I think it happens for any error, but in my case it was stale key for localhost.

### PR DESCRIPTION
**Pull request by chadoh**
I recommend reviewing the code [with indentation changes hidden](https://github.com/near/create-near-app/pull/398/files?diff=unified&w=1)

Fixes #391 by moving button disabling to vanilla/src/main.js, as this logic interferes with React's state management and breaks the React app

Fixes #397 (also fixes #70) by adding error handling to the setGreeting and moving form reenabling to the `finally` clause of the promise resolution

### CODE REVIEW

File: common/frontend/utils.js [hunk 1]
```diff
@@ -38,16 +38,22 @@ export async function onSubmit(event) {
   fieldset.disabled = true
 
   // make an update call to the smart contract
-  await contract.setGreeting({
```
Comment (vgrichina) [inline common/frontend/utils.js:41]: @chadoh why change from `async` / `await` to returning promise explicitly?

Comment (chadoh) [reply common/frontend/utils.js:39]: ...because I hadn't known about `try...catch...finally`

I've updated to use this syntax, thanks for teaching me!
